services:
  - type: web
    name: bank-cheque-verification
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn chequeprojet.wsgi --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 600"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: GEMINI_API_KEY
        sync: false
